name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build-ios:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
                                                        
      - name: Catch up # see https://github.com/actions/checkout/issues/439
        run: git pull origin ${{ github.ref }} --no-rebase

      - name: Build iOS
        uses: geode-catgirls/build-geode-mod@test
        with:
          combine: true
          gh-pat: ${{ secrets.GH_PAT }}
          cli: nightly
          # super secret
          
  package:
    name: Package and release mod
    runs-on: ubuntu-latest
    needs: ['build-ios']
    steps:
      - uses: geode-catgirls/build-geode-mod/combine@main
        id: build
        name: Combine mods

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
